---
- hosts: mywebservernodes 
  become: yes 
  vars:
     myvar1: tree 
     myvar2: wget 
     myvar3: git 
  tasks:
     - name: i want to display variable value
       debug: 
         msg: "{{myvar1}}"

     - name: i want to install all package on ubuntu node 
       apt: 
         name: "{{item}}"
         state: present
       when: ansible_os_family=="Debian"
       loop:
        - "{{myvar1}}"
        - "{{myvar2}}"
        - "{{myvar3}}"
        

  