--- 
- hosts: all 
  become: yes 
  tasks: 
      - name: i want install apache 
        apt: 
          name: apache2 
          state: present 
        when: ansible_os_family== "Debian"
          

        -name: i want to install webserver on redhat 