--- 
- hosts: mywebserver 
  become: yes 
  tasks: 
      - name: i want to install webserver on ubuntu node
        apt: 
          name: "{{mywebserveronubuntu}}" 
          state: present 
        when: ansible_os_family== "Debian"
          

      - name: i want to install ubuntu on redhat 
        yum:
          name: "{{mywebserveronredhat}}"
          state: present
        when: ansible_os_family== "RedHat"


